### ISSUE TITLE
Only list models that are available for use (maybe a bug)

### ISSUE THREAD

**Issue by limboy** [egoist/chatwise-releases#16]
<img width="408" alt="image" src="https://github.com/user-attachments/assets/4aba1cc4-72a9-4d72-993f-de30c0ddcc9d">

Can't understand the logic of this list.  While I haven't configured my OpenAI API key, it's included; however, other models without API keys are missing.

PS: The model provider and the models themselves seem too similar...

**Comment by egoist** [comment]
Yeah OpenAI models are always included at the moment, others requires an API to show up

**Comment by egoist** [comment]
just improved the readability:

![CleanShot 2024-12-12 at 15 26 06@2x](https://github.com/user-attachments/assets/dec9e4cd-7b92-4add-b9e4-42f1244ce38a)
