### ISSUE TITLE
Audio Generator seems not using OpenAI API Base URL

### ISSUE THREAD

**Issue by limboy** [egoist/chatwise-releases#17]
I’ve configured OpenAI’s API key and base URL in the settings panel, and it’s working fine for generating conversations. However, when I click the speaker icon below the AI’s response to generate audio, an error appears. It seems like the request is being sent directly to OpenAI.

<img width="377" alt="image" src="https://github.com/user-attachments/assets/2628eddc-a063-4af3-89ae-c8f56b5517b6" />

<img width="620" alt="image" src="https://github.com/user-attachments/assets/961d3709-f5e8-42f8-9ae5-dd1d235bf2a7" />

<img width="795" alt="image" src="https://github.com/user-attachments/assets/e722ecf6-6426-4f1f-92fe-5029e34cce9b" />

**Comment by egoist** [comment]
it requires OpenAI Whisper, and I believe OpenRouter does not offer text-to-speech models

**Comment by egoist** [comment]
I will add support for Groq.com later since it supports Whisper

**Comment by limboy** [comment]
yeah, that's what I thought after failed attempt, so I changed to another API Key / API Base URL combination, which works fine on ChatKit, but still failed on ChatWise.

https://github.com/user-attachments/assets/603c6f3d-b70a-4f73-a3cb-88ee9ca496a8

**Comment by egoist** [comment]
Fixed https://github.com/egoist/chatwise-releases/releases/tag/v0.2.1
