### ISSUE TITLE
Web search

### ISSUE THREAD

**Issue by egoist** [egoist/chatwise-releases#2]

**Comment by grikomsn** [comment]
I'd like to submit an issue about web search but since this ticket is still open, should I comment here or make a new one?

Actual issue:

> Current issue is I only have Chrome Dev and Chromium installed and ChatWise seems to only search default ones. Is there a way to customize/override browser path?
>
> ![CleanShot 2024-12-05 at 21 06 28@2x](https://github.com/user-attachments/assets/11ce9a4d-d5c9-48b3-9828-35e1da9476ce)

**Comment by egoist** [comment]
@grikomsn by default it performs a search using browsers installed on your computer, namely Chrome / Edge or Brave, do you have any of these installed?

An alternative is to use [Tavily](https://tavily.com/) for search in settings, which is also much faster:

![CleanShot 2024-12-12 at 12 57 10@2x](https://github.com/user-attachments/assets/cbfcc3dd-0bec-45f4-8fb3-c3f7864a6bdc)

**Comment by egoist** [comment]
@grikomsn ok i see your comment, will add Chrome Dev and Chromium too, btw you can also try Tavily for now

**Comment by grikomsn** [comment]
I'm already using Tavily since the browser mode does not work, but it'd be great if I can use existing browsers 😄

**Comment by egoist** [comment]
Just added Chromium support in v0.1.38
