### ISSUE TITLE
Some code highlighting support missing && App zoom is ineffective

### ISSUE THREAD

**Issue by imoyy** [egoist/chatwise-releases#21]
App version: 0.3.2
System Environment: macOS Sonoma 14.7.2 (Intel)

As the title says, some code highlighting is not yet supported. I tested and found this three: C, C++, and Kotlin. 
Also, the app's zoom, whether zoom in or out, doesn't work on my device, whether triggered by shortcuts or menu bar's options.

![CleanShot 2024-12-17 at 18 58 18@2x](https://github.com/user-attachments/assets/133fbda8-08cb-4927-a1ee-6ad300ff1097)

**Comment by egoist** [comment]
These languages are indeed missing and zoom in hasn't been implemented yet, will fix it in the next release
