### ISSUE TITLE
unable to select ElevenLabs as TTS option

### ISSUE THREAD

**Issue by limboy** [egoist/chatwise-releases#22]
I've configured ElevenLabs API Keys (also restarted ChatWise), but didn't find the option to choose ElevenLabs TTS

<img width="574" alt="image" src="https://github.com/user-attachments/assets/cc85c7f9-c841-44bf-8f91-2df04d2f9856" />
<img width="960" alt="image" src="https://github.com/user-attachments/assets/43890505-13e1-4116-8776-3ef6c575978b" />

**Comment by egoist** [comment]
It's in General
![CleanShot 2024-12-17 at 21 09 18@2x](https://github.com/user-attachments/assets/67aac574-603b-470b-9daa-d79d87f7de35)
