### ISSUE TITLE
Support Markdown

### ISSUE THREAD

**Issue by amsswd** [egoist/chatwise-releases#28]
能否让回答界面支持markdown渲染，很多公式看着费劲。支持

**Comment by egoist** [comment]
你是说回复里吗，是支持 markdown 的，不过暂不支持公式

**Comment by amsswd** [comment]
对，我的意思是公式还都是latex代码没有渲染

**Comment by egoist** [comment]
在 0.4 中已支持

**Comment by amsswd** [comment]
祝好！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年12月24日 23:08 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [egoist/chatwise-releases] Support Markdown (Issue #28) |

在 0.4 中已支持
