### ISSUE TITLE
failed to load config

### ISSUE THREAD

**Issue by trader108** [egoist/chatwise-releases#33]
<img width="341" alt="image" src="https://github.com/user-attachments/assets/4753ca82-e442-454b-b3dc-e6fc2fe5e040" />
when update to the latest version,the app can't use!Just like info. of the picture!

**Comment by trader108** [comment]
<img width="539" alt="image" src="https://github.com/user-attachments/assets/32c19fbf-8377-4c42-8483-bb0ed1577cb9" />
Has no place to set the API key for tavily.

**Comment by egoist** [comment]
fixed https://github.com/egoist/chatwise-releases/releases/tag/v0.4.7
